### ISSUE TITLE
How do you build this?

### ISSUE THREAD

**Issue by Arbifoxx** [fchb1239/AirJump#8]
How do you build this? I opened it in visual studio, and I get errors like

The type or namespace name 'UnityEngine' could not be found (are you missing a using directive or an assembly reference?)

**Comment by Crazby** [comment]
add dependencies

**Comment by fchb1239** [comment]
i don’t trust other peoples with knowing how to build my mod - also it’s not under a license meaning you can’t even legally build it so yah

**Comment by developer9998** [comment]
what a bitch

**Comment by Arbifoxx** [comment]
I did figure out how to do it, you go and add all the dlls as dependencies in vs and also the mod dependencies and the dlls from bepinex. Build and profit. Thx to Crazby

**Comment by gizmogoat** [comment]
> i don’t trust other peoples with knowing how to build my mod - also it’s not under a license meaning you can’t even legally build it so yah

What's the point of being an open source project if you refuse to help or allow potential contributors build your software like it's some sort of forbidden knowledge? It's not much better than just keeping your code hidden at that point.
The modding discord explicitly recommends having your code be under a license:
![image](https://user-images.githubusercontent.com/17483712/218518251-0a1ffe3c-0dbf-4d55-a860-62fba0544384.png)
Doing this would further the development of AirJump by promoting pull requests and collaboration.

Even if you _are_ concerned about cheaters, they have about 1500 different kinds of platforms in various different mod menus that aren't these.
Wasting your time trying to skid this version would be a bad idea, and even if they did, they wouldn't be sharing their source code so you could license under GNU GPL and then DMCA them. I don't see any point in doing this other than just pure authority of power.

If you **really** hate the idea of self compiling at least set up Github Actions or some sort of automated build system so we're not stuck with the half-broken outdated version of AirJump that's still somehow the latest release

**Comment by fchb1239** [comment]
> > i don’t trust other peoples with knowing how to build my mod - also it’s not under a license meaning you can’t even legally build it so yah
> 
> 
> 
> This isn't very in spirit of open source/FOSS.
> 
> What's the point of being an open source project if you refuse to help or allow potential contributors build your software like it's some sort of forbidden knowledge? It's not much better than just keeping your code hidden at that point.
> 
> The modding discord explicitly recommends having your code be under a license:
> 
> ![image](https://user-images.githubusercontent.com/17483712/218518251-0a1ffe3c-0dbf-4d55-a860-62fba0544384.png)
> 
> Doing this would further the development of AirJump by promoting pull requests and collaboration.
> 
> 
> 
> Even if you _are_ concerned about cheaters, they have about 1500 different kinds of platforms in various different mod menus that aren't these.
> 
> Wasting your time trying to skid this version would be a bad idea, and even if they did, they wouldn't be sharing their source code so you could license under GNU GPL and then DMCA them. I don't see any point in doing this other than just pure authority of power.
> 
> 
> 
> If you **really** hate the idea of self compiling at least set up Github Actions or some sort of automated build system so we're not stuck with the half-broken outdated version of AirJump that's still somehow the latest release

Just because I want to make something myself?

**Comment by developer9998** [comment]
Then at least state it somewhere and NOT make me waste hours of my time just to be told to work on something more valuable.

**Comment by fchb1239** [comment]
It's not my fault you went and fixed it, I never asked you to lol

**Comment by gizmogoat** [comment]
> Then at least state it somewhere and NOT make me waste hours of my time just to be told to work on something more valuable.

yeah dev fixed like 3 of your mods and you refused to do anything with it despite all you having to do is click "merge"
if you wanna work on something on your own at least maintain it properly

**Comment by developer9998** [comment]
> It's not my fault you went and fixed it, I never asked you to lol

What? Yeah I get that but to be told just that I should work on something more valuable and leave it at that is a dick move bro
![FD95C0A2-B8C3-4EA1-B30B-24D35FBDFE40](https://user-images.githubusercontent.com/81720436/218525237-e01c3856-3f9b-41a4-8d59-acbeb8b94174.jpeg)

**Comment by developer9998** [comment]
Also that's the whole point of pull requests

**Comment by fchb1239** [comment]
No need to be so aggressive, I'm just saying your efforts are being wasted. Sorry if I came of as rude when I stated that.

**Comment by developer9998** [comment]
I get I'm being agrressive but that's the whole point you essentially wasted my work I did for you while essentially ghosting me by not speaking about it the whole time.. 
![C4F932CC-54A8-4AC2-8CDF-1E9852A16A34](https://user-images.githubusercontent.com/81720436/218526030-34e9f732-5b1e-4a98-b30f-6717983e2315.jpeg)

Also about the game part, hypoctical knowing all you do now is just add onto your backrooms parts

**Comment by gizmogoat** [comment]
idk it kinda feels like if you did someones homework for them and then they complained that they didnt have to do anything

**Comment by fchb1239** [comment]
Could we take this to Discord to make communications faster. And also please calm down, I don't get why you are being so aggressive and angry with me.

**Comment by developer9998** [comment]
No I wont go to Discord, this has to done somewhere and I want that somewhere to be public information

Also yeah what Kaylie said is pretty much exactly what happened, I'm "aggressive" because of that and I'm mad at the fact my work went to waste

**Comment by fchb1239** [comment]
I mean yeah it can be public sure, then we can just do this in the modding Discord

**Comment by developer9998** [comment]
Funny you ignored my other thing

**Comment by fchb1239** [comment]
Just hop on Discord so we can discuss this correctly, meet me in pc-modding

**Comment by gizmogoat** [comment]
isnt discussion of topics the whole point of github issues too lmao

**Comment by fchb1239** [comment]
Yes but I prefer not to refresh my page every time I want to see if someone wrote something new

**Comment by developer9998** [comment]
Too bad lazy

**Comment by gizmogoat** [comment]
you don't?? im getting live updates right now

**Comment by Arbifoxx** [comment]
I know it’s not my place to say but I’m also getting live updates

**Comment by fchb1239** [comment]
GitHub for iPhone is a little shit so I don't lol

**Comment by gizmogoat** [comment]
> I did figure out how to do it, you go and add all the dlls as dependencies in vs and also the mod dependencies and the dlls from bepinex. Build and profit. Thx to Crazby

Things switched up lately and its harder to build now. Did you have any success with the newer commits since fchb for some reason refuses to have any sort of compilation instructions? Thinking of starting my own fork that has a bunch of extra things without all the janky semi closed-sourciness that we're having to deal with right now but it seems like the repo is intentionally set up to be hard to compile

**Comment by Arbifoxx** [comment]
I haven’t built it lately but I can try in a bit. That fork sounds like a great idea.

**Comment by crazbyy1** [comment]
why are yall taking on almost a year thingy

**Comment by crazbyy1** [comment]
also i forgot i talked on here lol

**Comment by gizmogoat** [comment]
> why are yall taking on almost a year thingy

AirJump is a broken buggy mess now and none of us can fix it
Platforms just randomly appear and stay there for no reason regardless of modded lobby or not

**Comment by developer9998** [comment]
> > why are yall taking on almost a year thingy
> 
> AirJump is a broken buggy mess now and none of us can fix it


https://user-images.githubusercontent.com/81720436/227081869-77456b84-c06e-43e9-8c99-f10b0a7917a3.mp4
